name: mobile_app_flet
description: "Flutter project for a Python Flet mobile app to mange the Ledstrips backends"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work:
dependencies:
  flutter:
    sdk: flutter

  # https://github.com/flet-dev/serious-python/releases
  serious_python: ^0.4.1
  # https://github.com/flet-dev/flet/releases
  flet: ^0.12.2
  path: ^1.8.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://github.com/flet-dev/serious-python/releases
  serious_python: ^0.4.1
  # https://github.com/flet-dev/flet/releases
  flet: ^0.12.2
  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages:
flutter:
  uses-material-design: true
#  plugin:
#    platforms:
#      android:
#        package: com.flet.serious_python
#        pluginClass: AndroidPlugin
#        ffiPlugin: true
#      ios:
#        pluginClass: SeriousPythonPlugin
#        ffiPlugin: true

  assets:
    - app/ledstrips.zip
